### ISSUE TITLE
SPN was not given Get,List access policies for the vault

### ISSUE THREAD

**Issue by ross-p-smith** [JimPaine/azure-terraform-bootstrapper#3]
When connecting Azure DevOps Library using an SPN rather than a user, the SPN does not have the correct Access Policies on the Vault

**Comment by JimPaine** [comment]
My view at the moment is that when I add the variable group in Azure DevOps pipelines and tell it to use the Key Vault for its secrets it creates a new SPN and updates the policies for you. As the bootstrapper is intended to be a run once this seems okay for now.

Going to close, but feel free to open a new item for feature request
